### ISSUE TITLE
Consider extending `markdown` grammar

### ISSUE THREAD

**Issue by rockorager** [kristoff-it/supermd#2]
I am working on getting the supermd parser into `nvim-treesitter`. One of the [maintainers](https://github.com/nvim-treesitter/nvim-treesitter/pull/7130) mentioned that since so much of this is similar to the existing markdown parser, the supermd parser could be simplified by being an extension.

**Comment by kristoff-it** [comment]
Thank you so much for this work, I'm generally aware of how extension works but I plan to diverge from markdown more seriously once I get into it. This initial version of the grammar is just so that people can hit the ground running when using Zine. 

I'll also leave a comment in the PR.

Thank you again for this work.
