### ISSUE TITLE
vscode: the Markdown preview button disappears when file language is set to SUperMD

### ISSUE THREAD

**Issue by Atomk** [kristoff-it/supermd#6]
VS Code allows to preview a Markdown file [directly in the editor](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview), if the file language is set to Markdown:
![image](https://github.com/user-attachments/assets/524db732-9f3b-4b5a-a5c5-645c71b2bf69)

_(the English text for the button is "Open Preview to the Side")_

When the language is set to SuperMD, manually or by the SuperMD extension, the markup is still highlighted normally but the preview button shown above disappears.

**Comment by kristoff-it** [comment]
I'm not 100% sure how that's provided by VSCode, but I guess it's most probably done by the builtin Markdown extension.

We could try to replicate the same behavior but the point of SuperMD is that it integrates with Zine to resolve things like links and assets, so the best way of getting a live preview is to have the development server running and keep the page you're editing open in a browser tab next to VSCode.

Closing since you can get live feedback with the dev server and there doesn't seem to be an easy way to integrate further with VSCode.

**Comment by Atomk** [comment]
The in-editor preview is real-time and pretty useful, I use it to check the formatting while I edit a file so I don't have to switch to the browser or save the file every time. I can live without that, I opened the issue because since the fix is just two clicks I thought this could be easy to solve (I am not familiar with VSCode internals though)
